server:
  port: 8022
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  healthcheck:
    enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 30

    ###hostname: feign                 # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 5
#    leaseRenewalIntervalInSeconds: 10
ribbon:
  eureka:
    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
### 参考：https://spring.io/guides/gs/client-side-load-balancing/
#eureka.client.healthcheck.enabled = true
#eureka.instance.leaseRenewalIntervalInSeconds = 5
#eureka.instance.leaseExpirationDurationInSeconds = 30
#eureka.instance.preferIpAddress=true